// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSR_hvuQzYpKKEh8Ql6U8VEqwxh0FHncU',
    appId: '1:145360500408:web:dc759b9dbe0b7bf4ce264d',
    messagingSenderId: '145360500408',
    projectId: 'ecommerce-kkn2023',
    authDomain: 'ecommerce-kkn2023.firebaseapp.com',
    storageBucket: 'ecommerce-kkn2023.appspot.com',
    measurementId: 'G-3QQQC0PH17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7LzJAo5eegG8St18yJpt1HDss5rhwBs',
    appId: '1:145360500408:android:0b155cc2845958efce264d',
    messagingSenderId: '145360500408',
    projectId: 'ecommerce-kkn2023',
    storageBucket: 'ecommerce-kkn2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXfP6viYibQ4ARPPvZDZ_9FnP8Ue_PH0',
    appId: '1:145360500408:ios:8da3e10e0c46a9cfce264d',
    messagingSenderId: '145360500408',
    projectId: 'ecommerce-kkn2023',
    storageBucket: 'ecommerce-kkn2023.appspot.com',
    iosClientId: '145360500408-a8re59a9ilfc1t41ibfmaldaj0nvgsta.apps.googleusercontent.com',
    iosBundleId: 'com.example.kknSiwalanMitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXfP6viYibQ4ARPPvZDZ_9FnP8Ue_PH0',
    appId: '1:145360500408:ios:8da3e10e0c46a9cfce264d',
    messagingSenderId: '145360500408',
    projectId: 'ecommerce-kkn2023',
    storageBucket: 'ecommerce-kkn2023.appspot.com',
    iosClientId: '145360500408-a8re59a9ilfc1t41ibfmaldaj0nvgsta.apps.googleusercontent.com',
    iosBundleId: 'com.example.kknSiwalanMitra',
  );
}
